build:
  environment:
    memcached:  true
    postgresql: false
    redis:      false

  nodes:
    php70:
      environment:
        php:
          version: 7.0.20
          ini:
            'short_open_tag': 'On'
      project_setup:
        after:
          - wget -q -O phpunit.phar https://phar.phpunit.de/phpunit-6.5.phar
          - chmod 755 phpunit.phar

    php71:
      environment:
        php:
          version: 7.1.6
          ini:
            'short_open_tag': 'On'

      project_setup:
        after:
          - wget -q -O phpunit.phar https://phar.phpunit.de/phpunit-6.5.phar
          - chmod 755 phpunit.phar

  dependencies:
    # Runs before inferred commands
    before: []
    # Overwrites inferred commands
    override:
      - true
    # Runs after inferred commands
    after: []

  # Run after dependencies
  project_setup:
    override:
      - git clone https://github.com/nafigator/Veles.git
      - cd Veles
      - git checkout $SCRUTINIZER_BRANCH
      - git clone https://github.com/nafigator/Veles-unit-tests.git Tests
      - wget -q -O phpcs.phar https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
      - chmod 755 phpcs.phar

  tests:
    override:
      -
        command: ./phpunit.phar -c Tests/scrutinizer-phpunit.xml --coverage-clover=/home/scrutinizer/build/coverage-report.xml
        coverage:
          file: coverage-report.xml
          format: php-clover

      - ./phpcs.phar --encoding=utf-8 --standard=phpcs.xml --ignore=Tests,vendor -w --colors .

checks:
  php: true

filter:
  excluded_paths:
    - Tests/*
