build:
    environment:
        php: '5.5.25'
        memcached: true

    dependencies:
        # Runs before inferred commands
        before: []
        # Overwrites inferred commands
        override: []
        # Runs after inferred commands
        after: []

    # Run after dependencies
    project_setup:
        before:
            - mysql -e 'CREATE DATABASE IF NOT EXISTS test'
        after:
            - rm -rf *
            - git clone https://github.com/nafigator/Veles.git
            - cd Veles

    tests:
        before:
            - git submodule add --name tests https://github.com/nafigator/Veles-unit-tests.git Tests
        override:
            -
                command: phpunit -c Tests/scrutinizer-phpunit.xml --stderr --coverage-clover=coverage-report
                coverage:
                    file: coverage-report
                    format: php-clover

checks:
    php: true

filter:
    excluded_paths:
        - Tests/*
