build:
  environment:
    php:
      version: 5.6.16
      ini:
        'short_open_tag': 'On'

    memcached: true
    postgresql: false
    redis: false
    mysql: false

  dependencies:
    # Runs before inferred commands
    before: []
    # Overwrites inferred commands
    override: []
    # Runs after inferred commands
    after: []

  # Run after dependencies
  project_setup:
    after:
      - rm -rf *
      - git clone https://github.com/nafigator/Veles.git
      - cd Veles
      - git checkout $SCRUTINIZER_BRANCH
      - git submodule add -f --name tests https://github.com/nafigator/Veles-unit-tests.git Tests
      - composer global require "phpunit/phpunit=5.4.*"

  tests:
    override:
      -
        command: phpunit -c Tests/scrutinizer-phpunit.xml --stderr --coverage-clover '../coverage-report'
        coverage:
          file: coverage-report
          format: php-clover

checks:
  php: true

filter:
  excluded_paths:
    - Tests/*
