branches:
  only:
    - master
    - development

sudo: false

language: php

php:
  - 5.6
  - 7.0.1
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

services:
  - memcached

before_install:
  - composer self-update
  - composer install --no-interaction

before_script:
  - wget -q -O phpcs.phar https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - chmod 755 phpcs.phar
  - git submodule add -f --name tests https://github.com/nafigator/Veles-unit-tests.git Tests
  - |
    case $TRAVIS_PHP_VERSION in
      5.6)
        PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"
        phpenv config-add Tests/travisci-5.6.ini
        ;;
      7.0.1)
        PHPUNIT_FLAGS="--exclude-group=memcache"
        phpenv config-add Tests/travisci-7.0.1.ini
        ;;
      nightly)
        PHPUNIT_FLAGS="--exclude-group=cache,memcacheraw,memcached --bootstrap=Tests/travisci-nightly-bootstrap.php"
        echo 'short_open_tag = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        ;;
      hhvm)
        PHPUNIT_FLAGS=""
        cat Tests/travisci.ini >> /etc/hhvm/php.ini
        ;;
    esac

script:
  - phpunit -c Tests/travisci-phpunit.xml --stderr $PHPUNIT_FLAGS
  - ./phpcs.phar --encoding=utf-8 --standard=phpcs.xml --ignore=Tests,vendor -w --colors .

after_script:
  - |
    if [[ $TRAVIS_PHP_VERSION = "5.6" ]]; then
      CODECLIMATE_REPO_TOKEN="9b68837f2ccc3206ed5d6f74fc9422423e35a4dd28ee48f161165bc0259fd692" ./vendor/bin/test-reporter --stdout > codeclimate.json
      curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.2-dev)' https://codeclimate.com/test_reports
    fi
