sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.4
      before_script: phpenv config-add travisci-5.4.ini
      script: phpunit -c travisci-phpunit.xml --stderr --coverage-clover build/logs/clover.xml
    - php: 5.5
      before_script: phpenv config-add travisci.ini
      script: phpunit -c travisci-phpunit.xml --exclude-group=apc --stderr --coverage-clover build/logs/clover.xml
    - php: 5.6
      before_script: phpenv config-add travisci.ini
      script: phpunit -c travisci-phpunit.xml --exclude-group=apc --stderr --coverage-clover build/logs/clover.xml

services:
  - memcached

before_install:
  - composer self-update
  - composer install --no-interaction
  - mysql -e "SET GLOBAL sql_mode='ANSI'";
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test'

after_script:
  - CODECLIMATE_REPO_TOKEN="9b68837f2ccc3206ed5d6f74fc9422423e35a4dd28ee48f161165bc0259fd692" ./vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.2-dev)' https://codeclimate.com/test_reports"
