language: php

php:
  - 5.4

services:
  - memcached

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - phpenv config-add travisci.ini

script:
  - phpunit -c travisci-phpunit.xml
