sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

services:
  - memcached

before_install:
  - composer self-update
  - composer install --no-interaction
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test'

before_script:
  - |
    case $TRAVIS_PHP_VERSION in
      5.4)
        PHPUNIT_FLAGS=""
        phpenv config-add travisci-5.4.ini
        ;;
      5.5)
        PHPUNIT_FLAGS=""
        phpenv config-add travisci.ini
        ;;
      5.6)
        PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"
        phpenv config-add travisci.ini
        ;;
      7.0)
        PHPUNIT_FLAGS="--exclude-group=cache,memcache,memcacheraw,memcached --bootstrap=Tests/travisci-nightly-bootstrap.php"
        phpenv config-add travisci.ini
        ;;
      nightly)
        PHPUNIT_FLAGS="--exclude-group=cache,memcache,memcacheraw,memcached --bootstrap=Tests/travisci-nightly-bootstrap.php"
        echo 'short_open_tag = On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        ;;
      hhvm)
        PHPUNIT_FLAGS=""
        cat travisci.ini >> /etc/hhvm/php.ini
        ;;
    esac

script:
  - phpunit -c travisci-phpunit.xml --stderr $PHPUNIT_FLAGS

after_script:
  - |
    if [[ $TRAVIS_PHP_VERSION = "5.6" ]]; then
      CODECLIMATE_REPO_TOKEN="9b68837f2ccc3206ed5d6f74fc9422423e35a4dd28ee48f161165bc0259fd692" ./vendor/bin/test-reporter --stdout > codeclimate.json
      curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.2-dev)' https://codeclimate.com/test_reports
    fi
