language: php

php:
  - 5.4

services:
  - memcached

before_script:
  - composer install --dev --no-interaction
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - phpenv config-add travisci.ini

script:
  - phpunit -c travisci-phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=9b68837f2ccc3206ed5d6f74fc9422423e35a4dd28ee48f161165bc0259fd692 ./vendor/bin/test-reporter
